config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    resources :subtasks, only: [:new, :create, :edit, :update, :destroy]
  end
  root "tasks#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_task, only: [:new, :create, :edit]
  before_action :set_subtask, only: [:edit, :update, :destroy]

  def new
    @subtask = Subtask.new
  end

  def create
    @subtask = @task.subtasks.new(subtask_params)
    if @subtask.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end


  def update
    if @subtask.update(subtask_params)
      redirect_to tasks_path
    else
      render :new
    end
  end

  def destroy
    @subtask.destroy
    redirect_to tasks_path
  end

  private
    def set_task
      @task = Task.find(params[:task_id])
    end

    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    def subtask_params
      params.require(:subtask).permit(:title, :description, :status)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @tasks = Task.includes(:subtasks)
  end

  def show
    @task.subtasks
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todotasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= form_for [@task, @subtask] do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h1>Edit Subtask</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/subtasks/new.html.erb
<h1>Add Subtask</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><b><%= task.id %></b></td>
        <td><b><%= task.title %></b></td>
        <td><b><%= task.description %></b></td>
        <td><b><%= task.status %></b></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Subtasks', new_task_subtask_path(task) %></td>
      </tr>
      <% task.subtasks.each do |sub| %>
        <tr>
          <td></td>
          <td><%= sub.title %></td>
          <td><%= sub.description %></td>
          <td><%= sub.status %></td>
          <td><%= link_to 'Edit', edit_task_subtask_path(task.id,sub.id) %></td>
          <td><%= link_to 'Destroy', [task, sub], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>



    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h1>TASK ID:<%= @task.id %></h1>
<table>
  <thead>
    <tr>
      <th>Title:</th>
      <th>description:</th>
      <th>Status:</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <td><%= @task.title %></td>
      <td><%= @task.description %></td>
      <td><%= @task.status %></td>
      <td><%= link_to 'Add Subtasks', new_task_subtask_path(@task) %></td>
    </tr>
  </thead>
  <tbody>
    <% @task.subtasks.each do |sub| %>
      <tr>
        <td><%= sub.title %></td>
        <td><%= sub.description %></td>
        <td><%= sub.status %></td>
        <td><%= link_to 'Edit', edit_task_subtask_path(@task.id,sub.id) %></td>
        <td><%= link_to 'Destroy', [@task, sub], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>






<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>